# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pinp_num <- function(x, y) {
    .Call('_buffr_pinp_num', PACKAGE = 'buffr', x, y)
}

paste_int <- function(row, col) {
    .Call('_buffr_paste_int', PACKAGE = 'buffr', row, col)
}

dupe <- function(vec) {
    .Call('_buffr_dupe', PACKAGE = 'buffr', vec)
}

rowSumsC <- function(mat) {
    .Call('_buffr_rowSumsC', PACKAGE = 'buffr', mat)
}

f1 <- function(mat, max_row) {
    .Call('_buffr_f1', PACKAGE = 'buffr', mat, max_row)
}

f2 <- function(mat, max_col) {
    .Call('_buffr_f2', PACKAGE = 'buffr', mat, max_col)
}

f3 <- function(mat) {
    .Call('_buffr_f3', PACKAGE = 'buffr', mat)
}

f4 <- function(vec) {
    .Call('_buffr_f4', PACKAGE = 'buffr', vec)
}

expand_gridC_2 <- function(vec1_1, vec1_2, vec2_1, vec2_2) {
    .Call('_buffr_expand_gridC_2', PACKAGE = 'buffr', vec1_1, vec1_2, vec2_1, vec2_2)
}

